export const USER_SIGN_UP = "USER_SIGN_UP";
export const USER_LOG_IN = "USER_LOG_IN";
export const GET_COURSE_LIST = "GET_COURSE_LIST";
export const GET_COURSE_CATEGORY = "GET_COURSE_CATEGORY";
export const GET_COURSE_DETAIL = "GET_COURSE_DETAIL";
export const GET_USER_INFO = "GET_USER_INFO";
export const EDIT_USER_INFO = "EDIT_USER_INFO";
export const SAVE_USER = "SAVE_USER";
export const FIND_INFO = "FIND_INFO";
export const REGISTER_COURSE = "REGISTER_COURSE";
export const GET_REGISTERED_COURSES = "GET_REGISTERED_COURSES";
export const SAVE_COURSE = "UPDATE_MODAL";
export const GET_USER_LIST = "GET_USER_LIST";
export const GET_FINDING_USER_LIST = "GET_FINDING_USER_LIST";

export const GET_UNREGISTER_USER_LIST_OF_COURSE = "GET_UNREGISTER_USER_LIST_OF_COURSE";
export const GET_WAIT_ACCEPT_USER_LIST_OF_COURSE = "GET_WAIT_ACCEPT_USER_LIST_OF_COURSE";
export const GET_REGISTERED_USER_LIST_OF_COURSE = "GET_REGISTERED_USER_LIST_OF_COURSE";

export const REGISTER_USER = "GET_REGISTER_USER";
export const DEREGISTER_USER = "DEREGISTER_USER";

export const GET_UNREGISTER_COURSE_LIST_OF_USER = "GET_UNREGISTER_COURSE_LIST_OF_USER";
export const GET_WAIT_ACCEPT_COURSE_LIST_OF_USER = "GET_WAIT_ACCEPT_COURSE_LIST_OF_USER";
export const GET_REGISTERED_COURSE_LIST_OF_USER = "GET_REGISTERED_COURSE_LIST_OF_USER";